### ISSUE TITLE
Add Pattern Programs

### ISSUE THREAD

**Issue by Anushka-codergirl** [Anushka-codergirl/Java-Programs#1]

**Comment by Procoder16** [comment]
@Anushka-codergirl Ma'am, I would like to contribute to this. But can you tell me what type of patterns you want.

I would love to do this.

**Comment by Procoder16** [comment]
@Anushka-codergirl, If I am free to add any pattern then pls assign me, I would add something interesting.

**Comment by Anushka-codergirl** [comment]
Okay Go!

**Comment by Procoder16** [comment]
Can you please assign me??

**Comment by Anushka-codergirl** [comment]
Yes 👍

**Comment by Procoder16** [comment]
Please assign me then.

**Comment by Anushka-codergirl** [comment]
You are free to contribute.

**Comment by Procoder16** [comment]
OK

**Comment by Procoder16** [comment]
I'll be making the PR soon.

**Comment by Procoder16** [comment]
I am getting the following error, please help.

remote: Permission to Anushka-codergirl/Java-Programs.git denied to Procoder16.
fatal: unable to access 'https://github.com/Anushka-codergirl/Java-Programs.git/': The requested URL returned error: 403

**Comment by Anushka-codergirl** [comment]
I don't why this error occurs. Try again.

**Comment by arpitjain22june** [comment]
i will be contributing to this

**Comment by Procoder16** [comment]
@Anushka-codergirl I added a pattern that would simply print K using the alphabets with the help of nested loops.

#22 

Pls review it and merge it with the master branch if you find if appropriate according to the requirements of the repository.

**Comment by SagarGi** [comment]
Hlw i have added PatternOne in the Pattern folder. Please review it Once and merge it.

**Comment by Procoder16** [comment]
@Anushka-codergirl was my contribution OK???

**Comment by GC2002** [comment]
Hi! I would like to contribute a pattern as well. Please assign.
