### ISSUE TITLE
Add Programs for Array Operations

### ISSUE THREAD

**Issue by Anushka-codergirl** [Anushka-codergirl/Java-Programs#3]

**Comment by KeerthanaHK** [comment]
Hi, Shall I work on this?

**Comment by aakash-hacks** [comment]
Hey there, I'd like to work on this

**Comment by Anushka-codergirl** [comment]
Hello @KeerthanaHK  and @aakash-hacks. You are free to contribute.

**Comment by aakash-hacks** [comment]
@Anushka-codergirl  please add hacktoberfest in topics or else our PRs won't be considered

**Comment by Anushka-codergirl** [comment]
Done. Check it.

**Comment by NayakNavin** [comment]
Hi,
Can i work on this ?
