### ISSUE TITLE
Add resources for learning Java

### ISSUE THREAD

**Issue by Anushka-codergirl** [Anushka-codergirl/Java-Programs#4]
Find good resources for learning Java.
Add resources in the README.md file in the LearningResources directory.

**Comment by mayorJAY** [comment]
Hi @Anushka-codergirl Can I work on this?

**Comment by ahmedashfaq027** [comment]
Hi @Anushka-codergirl 
Can i take this ticket?

**Comment by aditi597** [comment]
hey! I'd like to do it.
